name: 删除运行记录

on:
  workflow_dispatch:

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: 删除运行记录
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 0
